// Compiled by ClojureScript 1.9.227 {:target :nodejs}
goog.provide('contribution.styles');
goog.require('cljs.core');
goog.require('cljs_react_material_ui.core');
contribution.styles.theme_cyan = "#7cf8fa";
contribution.styles.theme_blue = "#2c398f";
contribution.styles.theme_green = "#23fdd8";
contribution.styles.theme_orange = "#ffd500";
contribution.styles.theme_gray = "#47608e";
contribution.styles.primary1_color = contribution.styles.theme_cyan;
contribution.styles.accent1_color = contribution.styles.theme_cyan;
contribution.styles.text_color = "rgba(0, 0, 0, 0.87)";
contribution.styles.fade_white_color = "rgba(255, 255, 255, 0.8)";
contribution.styles.fade_white_text = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"color","color",1011675173),contribution.styles.fade_white_color], null);
contribution.styles.palette = new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"primary1-color","primary1-color",-450634374),contribution.styles.primary1_color,new cljs.core.Keyword(null,"accent1-color","accent1-color",1074129898),contribution.styles.accent1_color,new cljs.core.Keyword(null,"text-color","text-color",1728708298),"#FFF"], null);
contribution.styles.mui_theme = cljs_react_material_ui.core.get_mui_theme.call(null,new cljs.core.PersistentArrayMap(null, 8, [new cljs.core.Keyword(null,"palette","palette",-456203511),contribution.styles.palette,new cljs.core.Keyword(null,"font-family","font-family",-667419874),"proxima-soft, sans-serif",new cljs.core.Keyword(null,"text-field","text-field",1955422445),new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"error-color","error-color",-332587474),contribution.styles.theme_orange,new cljs.core.Keyword(null,"floating-label-color","floating-label-color",673035050),"#FFF",new cljs.core.Keyword(null,"focus-color","focus-color",-1971091373),contribution.styles.theme_green,new cljs.core.Keyword(null,"disabled-text-color","disabled-text-color",1330689001),"rgba(255, 255, 255, 0.6)"], null),new cljs.core.Keyword(null,"paper","paper",-836673493),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"background-color","background-color",570434026),contribution.styles.theme_blue,new cljs.core.Keyword(null,"color","color",1011675173),"#FFF"], null),new cljs.core.Keyword(null,"raised-button","raised-button",1120646461),new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"primary-text-color","primary-text-color",-1255467826),contribution.styles.theme_blue,new cljs.core.Keyword(null,"primary-color","primary-color",-2081382435),contribution.styles.theme_green,new cljs.core.Keyword(null,"disabled-text-color","disabled-text-color",1330689001),contribution.styles.theme_blue,new cljs.core.Keyword(null,"disabled-color","disabled-color",1072841929),"rgba(255, 255, 255, 0.6)"], null),new cljs.core.Keyword(null,"drop-down-menu","drop-down-menu",92714161),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"accent-color","accent-color",908336425),contribution.styles.theme_blue], null),new cljs.core.Keyword(null,"menu-item","menu-item",-1371111773),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"selected-text-color","selected-text-color",-2046274829),contribution.styles.theme_cyan], null),new cljs.core.Keyword(null,"snackbar","snackbar",1792678973),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"background-color","background-color",570434026),"rgba(0, 0, 0, 0.95)",new cljs.core.Keyword(null,"text-color","text-color",1728708298),contribution.styles.theme_cyan], null)], null));
contribution.styles.desktop_gutter = (contribution.styles.mui_theme["spacing"]["desktopGutter"]);
contribution.styles.desktop_gutter_more = (contribution.styles.mui_theme["spacing"]["desktopGutterMore"]);
contribution.styles.desktop_gutter_less = (contribution.styles.mui_theme["spacing"]["desktopGutterLess"]);
contribution.styles.desktop_gutter_mini = (contribution.styles.mui_theme["spacing"]["desktopGutterMini"]);
contribution.styles.margin_bottom_gutter = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"margin-bottom","margin-bottom",388334941),contribution.styles.desktop_gutter], null);
contribution.styles.margin_bottom_gutter_more = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"margin-bottom","margin-bottom",388334941),contribution.styles.desktop_gutter_more], null);
contribution.styles.margin_top_gutter_more = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"margin-top","margin-top",392161226),contribution.styles.desktop_gutter_more], null);
contribution.styles.margin_bottom_gutter_less = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"margin-bottom","margin-bottom",388334941),contribution.styles.desktop_gutter_less], null);
contribution.styles.margin_bottom_gutter_mini = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"margin-bottom","margin-bottom",388334941),contribution.styles.desktop_gutter_mini], null);
contribution.styles.margin_top_gutter = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"margin-top","margin-top",392161226),contribution.styles.desktop_gutter], null);
contribution.styles.margin_top_gutter_less = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"margin-top","margin-top",392161226),contribution.styles.desktop_gutter_less], null);
contribution.styles.margin_all = (function contribution$styles$margin_all(x){
return new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"margin-top","margin-top",392161226),x,new cljs.core.Keyword(null,"margin-bottom","margin-bottom",388334941),x,new cljs.core.Keyword(null,"margin-right","margin-right",809689658),x,new cljs.core.Keyword(null,"margin-left","margin-left",2015598377),x], null);
});
contribution.styles.margin_horizontal = (function contribution$styles$margin_horizontal(x){
return new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"margin-right","margin-right",809689658),x,new cljs.core.Keyword(null,"margin-left","margin-left",2015598377),x], null);
});
contribution.styles.margin_vertical = (function contribution$styles$margin_vertical(x){
return new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"margin-top","margin-top",392161226),x,new cljs.core.Keyword(null,"margin-bottom","margin-bottom",388334941),x], null);
});
contribution.styles.padding_all = (function contribution$styles$padding_all(x){
return new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"padding-top","padding-top",1929675955),x,new cljs.core.Keyword(null,"padding-bottom","padding-bottom",-1899795591),x,new cljs.core.Keyword(null,"padding-right","padding-right",-1250249681),x,new cljs.core.Keyword(null,"padding-left","padding-left",-1180879053),x], null);
});
contribution.styles.padding_horizontal = (function contribution$styles$padding_horizontal(x){
return new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"padding-right","padding-right",-1250249681),x,new cljs.core.Keyword(null,"padding-left","padding-left",-1180879053),x], null);
});
contribution.styles.padding_vertical = (function contribution$styles$padding_vertical(x){
return new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"padding-top","padding-top",1929675955),x,new cljs.core.Keyword(null,"padding-bottom","padding-bottom",-1899795591),x], null);
});
contribution.styles.text_left = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"text-align","text-align",1786091845),new cljs.core.Keyword(null,"left","left",-399115937)], null);
contribution.styles.text_right = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"text-align","text-align",1786091845),new cljs.core.Keyword(null,"right","right",-452581833)], null);
contribution.styles.text_center = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"text-align","text-align",1786091845),new cljs.core.Keyword(null,"center","center",-748944368)], null);
contribution.styles.full_width = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"width","width",-384071477),"100%"], null);
contribution.styles.full_height = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"height","height",1025178622),"100%"], null);
contribution.styles.no_wrap = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"white-space","white-space",-707351930),new cljs.core.Keyword(null,"nowrap","nowrap",457264988)], null);
contribution.styles.word_wrap_break = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"word-wrap","word-wrap",-1700975926),new cljs.core.Keyword(null,"break-word","break-word",-153550263)], null);
contribution.styles.clickable = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"cursor","cursor",1011937484),new cljs.core.Keyword(null,"pointer","pointer",85071187)], null);
contribution.styles.display_inline = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"display","display",242065432),new cljs.core.Keyword(null,"inline","inline",1399884222)], null);
contribution.styles.display_block = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"display","display",242065432),new cljs.core.Keyword(null,"block","block",664686210)], null);
contribution.styles.italic_text = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"font-style","font-style",-773672352),new cljs.core.Keyword(null,"italic","italic",32599196)], null);
contribution.styles.bold_text = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"font-style","font-style",-773672352),new cljs.core.Keyword(null,"bold","bold",-116809535)], null);
contribution.styles.paper = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"border-radius","border-radius",419594011),"10px"], null);
contribution.styles.content_wrap = contribution.styles.padding_all.call(null,contribution.styles.desktop_gutter);
contribution.styles.white_text = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"color","color",1011675173),cljs_react_material_ui.core.color.call(null,new cljs.core.Keyword(null,"white","white",-483998618))], null);
contribution.styles.app_bar = new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"background-color","background-color",570434026),"#FFF",new cljs.core.Keyword(null,"box-shadow","box-shadow",1600206755),"none"], null);
contribution.styles.active_address_select_field = new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"color","color",1011675173),contribution.styles.theme_blue,new cljs.core.Keyword(null,"margin-right","margin-right",809689658),(10)], null);
contribution.styles.active_address_single = new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"margin-right","margin-right",809689658),(10),new cljs.core.Keyword(null,"font-size","font-size",-1847940346),"1.3em",new cljs.core.Keyword(null,"line-height","line-height",1870784992),"50px",new cljs.core.Keyword(null,"color","color",1011675173),contribution.styles.theme_blue], null);
contribution.styles.active_address_select_field_label = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"color","color",1011675173),contribution.styles.theme_blue], null);
contribution.styles.app_bar_balance = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"color","color",1011675173),contribution.styles.theme_blue], null);
contribution.styles.stats_tile_border_right = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"border-right","border-right",-668932860),"0.5px solid rgba(255, 255, 255, 0.1)"], null);
contribution.styles.stats_tile_border_bottom = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"border-bottom","border-bottom",2110948415),"0.5px solid rgba(255, 255, 255, 0.1)"], null);
contribution.styles.stats_tile_border_top = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"border-top","border-top",-158897573),"0.5px solid rgba(255, 255, 255, 0.1)"], null);
contribution.styles.stats_tile = new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"text-align","text-align",1786091845),"center",new cljs.core.Keyword(null,"height","height",1025178622),(250),new cljs.core.Keyword(null,"color","color",1011675173),contribution.styles.theme_green,new cljs.core.Keyword(null,"font-family","font-family",-667419874),"filson-soft, sans-serif"], null);
contribution.styles.stats_tile_title = new cljs.core.PersistentArrayMap(null, 7, [new cljs.core.Keyword(null,"text-transform","text-transform",1685000676),"uppercase",new cljs.core.Keyword(null,"font-size","font-size",-1847940346),"0.95em",new cljs.core.Keyword(null,"font-weight","font-weight",2085804583),"bold",new cljs.core.Keyword(null,"padding-bottom","padding-bottom",-1899795591),contribution.styles.desktop_gutter_less,new cljs.core.Keyword(null,"margin-bottom","margin-bottom",388334941),contribution.styles.desktop_gutter_less,new cljs.core.Keyword(null,"margin-left","margin-left",2015598377),contribution.styles.desktop_gutter_less,new cljs.core.Keyword(null,"margin-right","margin-right",809689658),contribution.styles.desktop_gutter_less], null);
contribution.styles.contrib_countdown_unit = new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"font-size","font-size",-1847940346),"0.9em",new cljs.core.Keyword(null,"width","width",-384071477),(60),new cljs.core.Keyword(null,"display","display",242065432),new cljs.core.Keyword(null,"inline-block","inline-block",1967810016),new cljs.core.Keyword(null,"text-align","text-align",1786091845),new cljs.core.Keyword(null,"left","left",-399115937)], null);
contribution.styles.contrib_countdown_value = new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"display","display",242065432),new cljs.core.Keyword(null,"inline-block","inline-block",1967810016),new cljs.core.Keyword(null,"font-size","font-size",-1847940346),"2.7em",new cljs.core.Keyword(null,"width","width",-384071477),(57)], null);
contribution.styles.logo = new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"height","height",1025178622),(45),new cljs.core.Keyword(null,"width","width",-384071477),"auto",new cljs.core.Keyword(null,"margin-top","margin-top",392161226),(13)], null);
contribution.styles.stats_tile_amount = new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"width","width",-384071477),"100%",new cljs.core.Keyword(null,"font-size","font-size",-1847940346),"3em",new cljs.core.Keyword(null,"display","display",242065432),new cljs.core.Keyword(null,"inline","inline",1399884222)], null);
contribution.styles.stats_tile_amount_subtitle = new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"width","width",-384071477),"100%",new cljs.core.Keyword(null,"font-size","font-size",-1847940346),"1.2em"], null);
contribution.styles.cap_progress = cljs.core.merge.call(null,contribution.styles.margin_bottom_gutter_less,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"height","height",1025178622),"10px",new cljs.core.Keyword(null,"border-radius","border-radius",419594011),"10px"], null));
contribution.styles.distribution_note = cljs.core.merge.call(null,contribution.styles.full_width,contribution.styles.fade_white_text,contribution.styles.margin_top_gutter,contribution.styles.fade_white_text,new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"font-size","font-size",-1847940346),"0.9em"], null));
contribution.styles.contrib_terms_link = new cljs.core.PersistentArrayMap(null, 6, [new cljs.core.Keyword(null,"background-color","background-color",570434026),contribution.styles.theme_cyan,new cljs.core.Keyword(null,"padding","padding",1660304693),"8px 13px",new cljs.core.Keyword(null,"font-size","font-size",-1847940346),"0.75em",new cljs.core.Keyword(null,"border-radius","border-radius",419594011),"20px",new cljs.core.Keyword(null,"color","color",1011675173),contribution.styles.theme_blue,new cljs.core.Keyword(null,"font-weight","font-weight",2085804583),"bold"], null);
contribution.styles.blob1 = new cljs.core.PersistentArrayMap(null, 6, [new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"top","top",-1856271961),(200),new cljs.core.Keyword(null,"left","left",-399115937),"-40%",new cljs.core.Keyword(null,"z-index","z-index",1892827090),(-1),new cljs.core.Keyword(null,"height","height",1025178622),(980),new cljs.core.Keyword(null,"margin-bottom","margin-bottom",388334941),(40)], null);
contribution.styles.blob2 = new cljs.core.PersistentArrayMap(null, 6, [new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"top","top",-1856271961),(300),new cljs.core.Keyword(null,"right","right",-452581833),"-30%",new cljs.core.Keyword(null,"z-index","z-index",1892827090),(-1),new cljs.core.Keyword(null,"height","height",1025178622),(800),new cljs.core.Keyword(null,"overflow","overflow",2058931880),new cljs.core.Keyword(null,"hidden","hidden",-312506092)], null);
contribution.styles.blob3 = new cljs.core.PersistentArrayMap(null, 6, [new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"right","right",-452581833),"14%",new cljs.core.Keyword(null,"z-index","z-index",1892827090),(-1),new cljs.core.Keyword(null,"height","height",1025178622),(250),new cljs.core.Keyword(null,"top","top",-1856271961),(1030),new cljs.core.Keyword(null,"margin-bottom","margin-bottom",388334941),(40)], null);
contribution.styles.blob4 = new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"position","position",-2011731912),new cljs.core.Keyword(null,"absolute","absolute",1655386478),new cljs.core.Keyword(null,"right","right",-452581833),"3%",new cljs.core.Keyword(null,"z-index","z-index",1892827090),(-1),new cljs.core.Keyword(null,"height","height",1025178622),(60),new cljs.core.Keyword(null,"top","top",-1856271961),(150)], null);

//# sourceMappingURL=styles.js.map